load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")

new_git_repository(
  name = "com_github_libevent_libevent",
  remote = "https://github.com/libevent/libevent",
  commit = "5df3037d10556bfcb675bc73e516978b75fc7bc7",
  build_file = "//libs:libevent.BUILD",
)